name: Build and push docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Docker Login
        uses: docker/login-action@v1
        with: 
          registry: ${{ secrets.PRIVATE_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}        
      - 
        name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: src/
          push: true
          tags: ${{ secrets.PRIVATE_REGISTRY }}/files.javiercampos.info:latest        
